- name: SetUpPrompt
  ansible.builtin.shell: set-prompt github-runner


- name: Create github directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory

- name: Download and Extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.321.0/actions-runner-linux-x64-2.321.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes

- name: Packages for the GitHub CLI
  ansible.builtin.get_url:
    url: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo

- name: Install github cli
  ansible.builtin.dnf:
    name: gh
    state: latest

- name: Grab Token
  ansible.builtin.shell: |
   gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/kuppalaORG/actions/runners/registration-token
  register: out
#  become_user: ec2-user # Token can be fetched by ec2-user as gh login was done by that user.

- name: Print token
  ansible.builtin.debug:
    msg: "{{ out }}"